site_name: GNPS2 Documentation
site_url: https://wang-bioinformatics-lab.github.io/GNPS2_Documentation/
edit_uri: https://github.com/Wang-Bioinformatics-Lab/GNPS2_Documentation/edit/master/docs/
repo_name: Wang-Bioinformatics-Lab/GNPS2_Documentation
repo_url: https://github.com/Wang-Bioinformatics-Lab/GNPS2_Documentation

nav:
    - About: index.md
    - Server Status: status.md
    - Accounts: accounts.md
    - File Upload: fileupload.md
    - Mass Spec File Conversion: 
        - File Conversion: fileconversion.md
        - Agilent: agilent_conversion.md
    - Overall Tool Index: toolindex.md
    - Analysis Workflow Index: workflowindex.md
    - GNPS2 USI: usi.md
    - IDBac:
        - IDBac Database Depositions: idbacdepositions.md
        - IDBac Analysis: idbacanalysis.md
        - Raw Bruker Data Conversion: idbacrawconversion.md
        - mzXML to mzML Conversion: idbacmzxmlconversion.md
    - FBMN:
        Agilent: agilent_fbmn.md
    - API: api.md
    - Logos: logos.md
    - GNPS2 Workflow Development: workflowdev.md
    - Join the GNPS2 community: community.md
    - Contact/Office Hours: contact.md

    
theme:
    name: material
    palette:
        primary: '#003DA5'
        accent: '#FFB81C'
    custom_dir: overrides
    features:
      - content.action.edit

extra:
    social:
        - type: 'github'
          link: 'https://github.com/Wang-Bioinformatics-Lab'

plugins:
    - search
    - git-revision-date-localized:
        type: datetime

markdown_extensions:
    - toc:
        permalink: true
    - admonition

extra:
  analytics:
    provider: umami
