name: Auto Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test Build
      run: |
        mkdocs build -s
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        PERSONAL_TOKEN: ${{ secrets.TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: site
